#!/usr/bin/env bash

LATITUDE=$(echo $1 | cut -f2 -d=)
LONGITUDE=$(echo $2 | cut -f2 -d=)
RADIUS=$(echo $3 | cut -f2 -d=)

cd backend
poetry run python backend/load_data.py --latitude $LATITUDE --longitude $LONGITUDE --radius $RADIUS
